### ISSUE TITLE
Tags页面，搜索时LOGO有问题

### ISSUE THREAD

**Issue by phodal** [SegmentFault/report#163]
按Command + F即搜索的时候
![screen shot 2015-01-14 at 23 31 14](https://cloud.githubusercontent.com/assets/472311/5741344/77c9b730-9c45-11e4-80fc-fa65ab91b3b7.png)

**Comment by fenbox** [comment]
这个其实不算 bug，这是为了让某些图片表示的内容也能被正确的搜索到
