### ISSUE TITLE
撰写文章无法写自己的博客

### ISSUE THREAD

**Issue by tianshaokai** [SegmentFault/report#164]
网站上显示我已经通过申请，但是点击写博客，还是提示这个 ： “你的博客功能还没有开通, 请先申请”，请解决这个问题。

**Comment by fenbox** [comment]
你的用户名是什么

**Comment by tianshaokai** [comment]
1575640686@qq.com

**Comment by Integ** [comment]
已经可以了，你可以再试试。

**Comment by tianshaokai** [comment]
嗯嗯好了，谢谢啦，  原来不能用是怎么回事啊？？

**Comment by Integ** [comment]
应该是申请通过后，又被管理员误操作或其他原因给关闭了博客功能。

--
Yours faithfully Integrity

2015-02-11 13:17 GMT+08:00 田绍凯 <notifications@github.com>:

**Comment by tianshaokai** [comment]
嗯嗯，谢谢啦，
