### ISSUE TITLE
关于微博在firefox登陆

### ISSUE THREAD

**Issue by leeir** [SegmentFault/report#165]
微博在firefox不能正常登陆

**Comment by fenbox** [comment]
firefox 什么版本的？我这边测试没发现问题

**Comment by Integ** [comment]
新浪微博登陆的确定按钮需要点两下才行。
![image](https://cloud.githubusercontent.com/assets/1772687/5951565/31aad9c2-a7a4-11e4-94b8-f2bb70354fff.png)

**Comment by leeir** [comment]
这个页面我这边是走到的，微博登陆和允许授权之后，然后在回调到segmentfault页面上并没有登陆成功 ，还是立即登陆     firefox版本35.0

**Comment by Integ** [comment]
谢谢反馈，领取"找bug小能手"纪念品请私信官方微博（@SegmentFault）
