### ISSUE TITLE
无法修改自己的答案，点击“提交编辑”后出错

### ISSUE THREAD

**Issue by huandu** [SegmentFault/report#167]
console 里始终显示下面的错误：

```
Failed to load resource: the server responded with a status of 404 (Not Found)
Ajax 404:  /api/answer/1020000002519097/edit?_=23ae66e213efda498f2a4d25f33d80f5
editAnswer.a44c3a19.js:3
```

出问题的链接：http://segmentfault.com/q/1010000002516715/a-1020000002519097/edit?draftId=1220000002555182

**Comment by lvye** [comment]
http://segmentfault.com/q/1010000002554342

我们会尽快联系上线人员解决这个问题

**Comment by joyqi** [comment]
清除一下缓存试试，前端开发者测试没有问题 @Integ
