### ISSUE TITLE
域名迁移后，首页部分链接无法访问

### ISSUE THREAD

**Issue by Alex987965** [SegmentFault/report#169]
如图所示，点击之后跳转到.com域名，无法访问，请即时修正！
![qq20150309-1 2x](https://cloud.githubusercontent.com/assets/1943787/6556237/2d1fb892-c6a7-11e4-8bcc-1b31fa7e49b3.png)

![image](https://cloud.githubusercontent.com/assets/1943787/6556245/3cdc5cf4-c6a7-11e4-9440-7362c0f9f5d4.png)

**Comment by Integ** [comment]
链接已修复，谢谢反馈。

**Comment by Alex987965** [comment]
OK
