### ISSUE TITLE
刷新页面样式乱了, 我今天看网站 css 文件好像找不到了

### ISSUE THREAD

**Issue by yangman-c** [SegmentFault/report#170]
我用 MAC 系统, 浏览器Safari 版本 7.1 (9537.85.10.17.1), 网络: 电信+云梯翻墙
但是不翻墙的情况下, 样式是好的.

**Comment by lvye** [comment]
又拍云在国外解析并不流畅，所以建议不要在翻墙情况下访问

**Comment by joyqi** [comment]
再试试，我优化了下国外线路
