### ISSUE TITLE
表单提交问题。

### ISSUE THREAD

**Issue by Phieo** [SegmentFault/report#171]
我发现一个表单提交问题，但是不知道提交到哪里去，你们的readme写的也不够具体啊。。。

**Comment by Integ** [comment]
截个图发到这里就可以。

**Comment by Phieo** [comment]
产生过程: 添加文章到收藏夹，新建收藏夹的时候产生 期望结果: 创建成功 实际结果: 点击提交按钮无效 附件: ![image](https://cloud.githubusercontent.com/assets/10499704/6861485/e38f4958-d471-11e4-8d43-ae952c1493bb.png) 环境: os x 10.10，chrome等等

**Comment by Integ** [comment]
谢谢反馈，纪念品请私信官方微博（ @SegmentFault ）领取。
