### ISSUE TITLE
SegmentFault 关注标签问题高亮

### ISSUE THREAD

**Issue by D-ZL** [SegmentFault/report#172]
今天上SegmentFault 突然感觉那里不对原来是与关注标签相关问题不高亮。
![image](https://cloud.githubusercontent.com/assets/8456085/6932481/7df2f39a-d84c-11e4-93e6-96d5e5172b94.png)
原以为是去了，结果点开单个标签问题突然发现标签高亮有的有有的没有可能和关注的标签有关，如果问题打的标签你好像关注两个以上他会高亮，但是如果问题打的其中一个标签他不会高亮，还有就是问题打的单个标签好像也是不会高亮的。
![image](https://cloud.githubusercontent.com/assets/8456085/6932492/a540a99c-d84c-11e4-8e17-563a1ebd891e.png)

**Comment by Integ** [comment]
谢谢反馈，已修复上线
