### ISSUE TITLE
被隐藏的帖子如何显示出来呢

### ISSUE THREAD

**Issue by tianshaokai** [SegmentFault/report#173]
我发表的帖子被隐藏了，不知道如何显示出来

**Comment by Integ** [comment]
你好，
如果是自己发的文章被隐藏，可以点击文章最后的“显示”按钮
如果是问题被隐藏，可以把问题的ID发给管理员，帮你看一下。
答案是不能被隐藏的。

**Comment by tianshaokai** [comment]
我怎么提交给 管理员，请说一下吧

**Comment by Integ** [comment]
只要在社区建设的板块（ http://segmentfault.com/0x ）提个问题就好

--
Yours faithfully Integrity

2015-04-14 10:53 GMT+08:00 田绍凯 <notifications@github.com>:
