### ISSUE TITLE
无已发布文章时，文章草稿无法再次编辑

### ISSUE THREAD

**Issue by leanplay** [SegmentFault/report#174]
产生过程：在新开通写文章权限后，还没有已发布文章时，写了文章的草稿无法再次编辑，点编辑草稿会跳转至发布新文章，而不是编辑上次的草稿。
期望结果：进入草稿编辑页面
实际结果：进入创建新文章页面
环境：Macbook Air 10.10.1 (14B25)，Chrome 42.0.2311.90 (64-bit)

**Comment by lvye** [comment]
http://segmentfault.com/q/1010000002693152

此问题已经修复，需要等待上线

**Comment by leanplay** [comment]
好的。谢谢。
