### ISSUE TITLE
领奖了，bug 2 枚

### ISSUE THREAD

**Issue by daizhan** [SegmentFault/report#175]
第一个 消息推送内容错误。
![image 2](https://cloud.githubusercontent.com/assets/5318547/8147960/48b6edb2-12b7-11e5-93db-634edce77ff5.png)
用户没有接受我的答案，却告诉用户接受了我的答案。 声望倒是正常，没有加声望。
第二个 无法删除答案，直接报404 错误
![image 1](https://cloud.githubusercontent.com/assets/5318547/8147965/7adea64a-12b7-11e5-86cb-edbd84685c01.png)
弄的我好心慌，回答错了都删不了，幸好修改还可用。 

有图有真相，嘿嘿。 

另外说个题外话， 你们有打算在深圳招人吗？

**Comment by coffeesherk** [comment]
我碰到的情况是，用户接受了你的答案，然后又取消了会有这种情况。。

**Comment by daizhan** [comment]
那个无法删除的每人处理吗？  提了好几天了。

**Comment by lvye** [comment]
可以把不能删的回答和报错的response信息贴出来吗？

另外报bug建议到http://segmentfault.com/0x，这样方便处理。

**Comment by daizhan** [comment]
我有贴图， 你们不能根据那个链接追踪到是哪个答案吗？ 

我就是从那个页面过来的， 
![image 1](https://cloud.githubusercontent.com/assets/5318547/8203377/f103cd38-1513-11e5-85e8-ea0ded82675a.png)
是我点错了吗？ 

突然感觉segmentfault 有点。。。 

用户愿意提bug已经很是支持了， 反馈慢就算了，给出的信息还要重复几次， 不太像之前的segmentfault了。

**Comment by lvye** [comment]
@daizhan 因为我本地这边测试是ok，所以希望你能把你的response信息反馈过来，因为如果很大情况下会返回报错信息。

至于反馈不及时是因为我们这周刚好搬新的地方，加上运营人员都不在，再加上上周末我拔了智齿，一直在肿痛，效率非常低，实在抱歉。
