### ISSUE TITLE
无法收到激活邮件

### ISSUE THREAD

**Issue by AngleZhou** [SegmentFault/report#176]
我前一天晚上在手机上注册了，因为手机没配置邮箱，就没有激活。然后第二天发现邮箱里的激活邮件已经失效了。再次登陆发送激活邮件就再也收不到邮件了，邮箱里广告邮件，订阅邮件，垃圾邮件都找遍了，都没有。
不能激活！
好郁闷！

**Comment by joyqi** [comment]
请告诉我你的邮箱

**Comment by lvye** [comment]
根据github邮箱zhouq87724@163.com，已经手动激活。

**Comment by AngleZhou** [comment]
谢谢


发自网易邮箱大师
在2015年06月17日 13:11，Michael Fu 写道:

根据github邮箱zhouq87724@163.com，已经手动激活。
