### ISSUE TITLE
企业用户地点编辑提交问题

### ISSUE THREAD

**Issue by oo123ooiiiii** [SegmentFault/report#179]
首次工作地点添加，没有选择城市的时候无法保存，没有看到报错。
看上去像保存了，但是切换到别的地方又没了。
第二条倒是不选城市没有问题。

（凭印象报告，没有重试）

**Comment by Integ** [comment]
谢谢反馈，我们正在优化报错提示。
输入城市的问题正在着手解决。

**Comment by wtser** [comment]
花了1周做了typeHelper组件，然后重构了城市输入
