### ISSUE TITLE
重大BUG

### ISSUE THREAD

**Issue by GdSZzL** [SegmentFault/report#181]
其他功能不正常可以，但是我在网站注册了，你们发的验证邮箱起码得发到我邮箱上啊。。。不然我连这软件都使用不了了。还以为是网络延迟，但是也没理由延迟一个晚上（我的邮箱保证正确，亲试好几次）

**Comment by joyqi** [comment]
你好，你的邮箱地址是？

**Comment by GdSZzL** [comment]
我的用户名是GdZzL

**Comment by Integ** [comment]
邮件服务的问题，已修复。
