### ISSUE TITLE
邮箱无法激活

### ISSUE THREAD

**Issue by ghost** [SegmentFault/report#183]
注册后，收到了注册邮件。但是激活邮箱的时候，死活收不到激活邮件，垃圾邮件，广告邮件都找了。没有激活邮件，
该怎么办？

**Comment by lvye** [comment]
你可以等几分钟后再次点击发送验证邮箱，如果还是不行，可以这里回复邮箱地址，我们手动激活。

**Comment by songjyf** [comment]
确实不行，尝试了很多次，并且还换了邮箱 我的邮箱是
songjyf@126.com
麻烦帮我手动激活一下。
谢谢。

**Comment by lvye** [comment]
后台没有搜到该邮箱对应的用户，你能给一下个人主页地址吗？
例如：http://segmentfault.com/u/lvye

**Comment by songjyf** [comment]
https://github.com/songjyf

我想我估计是来错地方了。

**Comment by lvye** [comment]
其实我的意思是因为搜该邮箱没有成功，我想通过个人主页的用户名来搜。

所以你能提供一下在segmentfault.com的个人主页吗，譬如
http://segmentfault.com/u/lvye

在个人主页，我们能直接操作激活。
