### ISSUE TITLE
从剪贴板粘贴图片上传不能用了

### ISSUE THREAD

**Issue by jamesfancy** [SegmentFault/report#185]
就是粘贴图片的时候提示“上传的文件不是合法图片”，最近才出现的

http://segmentfault.com/q/1010000003506424
http://segmentfault.com/q/1010000003574190

**Comment by Integ** [comment]
谢谢反馈，上传 base64 格式的图片接口出现问题，正在修复

**Comment by Integ** [comment]
已修复，
感谢你对 SegmentFault 的支持。
欢迎常来逛逛。
