### ISSUE TITLE
发现bug一个

### ISSUE THREAD

**Issue by NaMaple** [SegmentFault/report#189]
提问时添加的ThinkPHP标签，发现不对修改为WordPress标签，但是在个人页面，标签饼装图中并没有修改。
![image](https://cloud.githubusercontent.com/assets/11288582/9896014/2346ae2c-5c69-11e5-957b-19653cde068c.png)

**Comment by lvye** [comment]
很有意思的bug，我们会马上修复

**Comment by lvye** [comment]
由于擅长标签是每天定期跑，数据会有缓存，目前暂时不能做到实时。
