### ISSUE TITLE
APP 【发现】--【动态】打开提示‘网络不给力’

### ISSUE THREAD

**Issue by syaka-yin** [SegmentFault/report#192]
APP客户端，【发现】--【动态】打开，始终无法刷新出内容，提示网络不给力，但是网络实际上是没问题的。
![segmentfault](https://cloud.githubusercontent.com/assets/4370991/10387922/e7e8bac8-6e97-11e5-9d2d-91392dc4ef13.png)

**Comment by wtser** [comment]
经过测试，现在不存在这个问题。
