### ISSUE TITLE
改进: 请问 sf 怎么对在社区里刷分的这种行为进行处理

### ISSUE THREAD

**Issue by xqin** [SegmentFault/report#194]
举例1:  某人注册小号, 只要养上一段时间积分整够15分(符合社区规则可以给别的回答/提问点赞).

![image](https://cloud.githubusercontent.com/assets/1265888/10600337/a5f65992-773c-11e5-84bd-087c32c4555b.png)

像这种现象怎么处理?  sf 是否有机制去检测这种行为, 还是单纯的, 不举报不追究?

举例2:  社区里的某人看另外一个不顺眼,  批量去将这个人的 提问/回答 都点赞, 
而这种积分行为社区又是怎么个处理法? 怎么界定他是被人恶意点的, 还是他自己用另外的账号去刷的.

还有, 在社区里给别人点赞 是不是设定的积分下线太低了?

![image](https://cloud.githubusercontent.com/assets/1265888/10600424/4ab51e00-773d-11e5-97ef-a22f47e5735f.png)

**Comment by joyqi** [comment]
你说的这个情况确实存在，我们正在开发新的用户处理机制，它有如下特点

1. 可以很方便地回滚用户的恶意行为
2. 可以快速处理用户举报
3. 可以配合机器人快速寻找出潜在的恶意行为

**Comment by xqin** [comment]
感谢您的快速回复, 期待着您所描述的功能能尽快上线. 谢谢.

**Comment by lvye** [comment]
我们最近的重点就是完善社区机制。
目前我们即将要做的：
一、优化举报和申诉机制，一旦用户发现类似问题，可以马上举报，运营人员会马上处理。
二、完善处罚机制，增加处理的手段和力度，譬如可以封禁用户“踩”的权限一周

**Comment by li2** [comment]
我发现了另一种刷分行为，与养小号刷分不同，是抱团刷分。这些人几乎是“全栈”工程师，提出的问题数天内在各种主题无缝切换android, ios, C#, python, php, 单片机, bootstrap.... 几个人互提问题、互答问题，一句话问题，几分钟后，一句话答案。。。如果这些行为多了，我认为SF的声望就会『通货膨胀似的贬值』（而我回答一个问题却要费好些时间（ orz...

**Comment by fenbox** [comment]
相关机制我们已经上线，将持续监测测试一段时间，并已封禁了部分用户
