### ISSUE TITLE
疑问: 关于回答被采纳之后, 提问者又采纳了其他人(或者说自己)的回复的疑问

### ISSUE THREAD

**Issue by xqin** [SegmentFault/report#198]
以这个为例:  http://segmentfault.com/q/1010000003859852?_ea=414967

该问题是于 10月15号 提出的, 我于 10月15号 进行了回复, 且发帖人也采纳了答案.
![image](https://cloud.githubusercontent.com/assets/1265888/10708501/548355ca-7a3d-11e5-8cd3-e60c86db5b9e.png)

然后, 今天 10月24号,楼主编辑了自己的回复内容, 然后采纳了自己.
![image](https://cloud.githubusercontent.com/assets/1265888/10708509/a7473b78-7a3d-11e5-9a21-609d793f8948.png)

我想问一下, 这种行为,是不是对回答者的不尊重? 社区是否对这种行为要进行约束或者说限制?
以及和积分相关的, 我的积分是不是被默默的减去了(因为我在声望记录里找不到以前增加积分的记录了),而且也没通知(我记得以前被取消采纳是有通知的)?

>PS: 当被采纳的回复被取消采纳之后,你们们不声不响的在之前被采纳的那个的声望记录里,清除被采纳时增加积分的那个记录, 不过还好消息通知里,没有清除,否则我现在就不着我的回复被采纳的证据了.你们这么做是不是不太地道了?为什么不是再新增一条(如果记录可以被默默的清除,那它还叫什么`记录`,产品明白`记录`二字的含义吗?),回复被取消采纳,积分减xx?以及对这个操作有疑问,是否可以提交申诉?

**Comment by lilydjwg** [comment]
> 这种行为,是不是对回答者的不尊重

是！

**Comment by wtser** [comment]
对该答案做了忽略处理

**Comment by lilydjwg** [comment]
@wtser 也就是说，用户 B 提出了问题 Q。用户 E 作出了回答并被 B 采纳。然后 B 又创建回答「这个问题已经解决了，谢谢 E」并采纳之，那么在计分上相当于 B 创建的回答不存在？于是问题 Q 并没有任何被采纳的回答。E 在 SF 的回答也没有因为实际上解决了问题 Q 而被计分？

而在视觉上，它相当于这个问题得到了一个莫名其妙的「正确答案」？

**Comment by xqin** [comment]
这个不是把那个人的答案忽略了, 就解决问题了, 要忽略他的答案,我目前的积分,也是可以允许我这么做的.

我们现在讨论的是, 出现这种情况的时候, SF 怎么保证 帮助他解决了问题, 但却得不到积分的问题.

以及像 用户 B的这种行为是不是应该有所限制, 以及 问题的提出者,  是不是不应该允许他采纳自己的回答?

**Comment by joyqi** [comment]
实际上我们是无法强制用户来采纳我们认为合理的答案的，stackoverflow上也有很多采纳的答案并不是最佳答案的情况。

但我们计划增加一个机制，就是众包定期review的机制，我们会把用户标记的，有可能被忽略了的最佳答案，放到一个列表中，让有经验的用户重新集中评分。

在 2015年11月6日 下午6:05，小秦 <notifications@github.com>写道：

**Comment by xqin** [comment]
那关于 不声不响的  把 采纳的那条记录 清除了 是不是不太符合常理?
为什么不能增加一条 记录 你在 xxx中的回答被取消采纳, 左边显示积分减多少. 这种的.

**Comment by lilydjwg** [comment]
@joyqi 要做的不是「强制用户来采纳我们认为合理的答案」，面是**引导用户来采纳他们认为有帮助的答案**。我见过不少次，用户得到了对他有帮助的答案，但是还是采纳了自己表示「问题已经解决，谢谢各位」的回答——他们把问答网站当成了论坛，并没有意识到「采纳」这一行为本身就表达了他们想表达的意思。

其实 SegmentFault 一直以来和 StackOverflow 有一个很微妙的不同：SO 默认显示少量评论，而 SF 必须在评论被 upvote 之后才能显示。你们想想，这向提问者传达了什么信息？

这是在告诉提问者，你的评论不重要，大多数人会看不到。所以提问者只好通过「补充问题」或者「添加回答」的方式来进行回应。

提问者也不一定清楚，「采纳」这一行为会奖励回答者。提问者更不知道，当有两个或两个以上的回答都在一定程度上帮助了他时，他该怎么做。

**Comment by li2** [comment]
非常赞同 @lilydjwg 的看法，好多人特喜欢把答案当评论用，简直就成了论坛中的跟帖行为了。
另外，即使已经有了可以解决问题的答案，还是有人喜欢做同质化的回答，不晓得去“赞”已有的答案，像这个问题：
http://segmentfault.com/q/1010000004066230
几乎不算个问题，所以我在评论中做了回答，当然别人不点开的话是看不见的。
而题主采纳了一个既不是最早回答的，也不是最优的答案。orz
@wtser @joyqi @fenbox

**Comment by LiXiaoRan** [comment]
凑个热闹
