### ISSUE TITLE
通知页面没有正确处理 HTML entity

### ISSUE THREAD

**Issue by lilydjwg** [SegmentFault/report#199]
如图：
![_001](https://cloud.githubusercontent.com/assets/440661/10792988/00d4cc7a-7dca-11e5-9f43-327c661db186.png)

**Comment by joyqi** [comment]
ok, got

**Comment by xqin** [comment]
bug 修的不积极, 其实这个bug我在 2015-10-19 号就已经反馈过了, 然后到了 28号还没修复.
![image](https://cloud.githubusercontent.com/assets/1265888/11138806/0fe0fd76-8a02-11e5-9d1d-8473d6489136.png)

**Comment by joyqi** [comment]
不知道你看的啥时候的版本，我们早就修复了
![2015-11-13 2 03 01](https://cloud.githubusercontent.com/assets/59437/11139857/56f771c4-8a0f-11e5-84bc-cf2ef091ce8e.png)
