### ISSUE TITLE
密码重置链接长期有效

### ISSUE THREAD

**Issue by mstm2014** [SegmentFault/report#200]
如题，邮箱中收到的密码重置链接，使用多次后仍然有效，请问是有时效设置吗？

**Comment by lvye** [comment]
是的，是有时效的，因为QQ等邮箱会去爬邮件链接，导致链接失效，所以目前是一定时间内还是可用的，但是是和用户绑定的，其它用户用不了这个code。

**Comment by mstm2014** [comment]
恩 已经失效了。建议在重置成功后销毁一下这个code，如果code泄漏也会比较麻烦。
