### ISSUE TITLE
邮箱无法激活或者更换

### ISSUE THREAD

**Issue by chang0022** [SegmentFault/report#201]
BUG：邮箱无法激活或者更换
过程：注册帐号邮箱填写错误，但是注册成功了。然后再帐号设置里面修改邮箱一直收到不到邮件，然后换了163的，qq的都不行。
环境: Mac Chrome

**Comment by lvye** [comment]
我们的邮件服务跪了，我们会马上修复

**Comment by chang0022** [comment]
嗯，刚已经收到N邮件。

**Comment by lvye** [comment]
带来困扰，十分抱歉。

**Comment by chang0022** [comment]
太客气了。
