### ISSUE TITLE
改进: sf markdown 中关于 标题/分隔符 在使用时遇到的问题

### ISSUE THREAD

**Issue by xqin** [SegmentFault/report#203]
首先先看一下 sf 上关于 `markdown` 的使用说明:
标题:
![image](https://cloud.githubusercontent.com/assets/1265888/11138932/bf1f6f1a-8a03-11e5-87a3-d50123244574.png)
分隔符:
![image](https://cloud.githubusercontent.com/assets/1265888/11138934/c48b7ae8-8a03-11e5-9eb4-4929c8fd34ab.png)

而目前在使用时, 标题充当了 分隔符的功能, 见下图:
![image](https://cloud.githubusercontent.com/assets/1265888/11138938/e49c6900-8a03-11e5-8104-ceb0e4c09a21.png)

而在使用分隔符的时候(三个减号), 它又充当了标题的功能:
![image](https://cloud.githubusercontent.com/assets/1265888/11138943/fb6c9e3e-8a03-11e5-8c5d-df32d09636a5.png)

希望改进后的效果为:  
三个减号 转换为一个分隔符, 它上一行的内容不要转换为标题.
而在使用 多个 `-` (不等于3) 时, 才产生将上一行转换为标题的功能.

**Comment by joyqi** [comment]
不可能以是不是三个减号来判断是不是分隔符，现在的处理没有问题。当你需要作为分隔符使用时，前后都隔一行，这样不论在展现时或者在编辑器里都可以展现为一个分隔符的样子。

**Comment by xqin** [comment]
那请问 规则 为什么这么写?
![image](https://cloud.githubusercontent.com/assets/1265888/11139389/b6e3cee4-8a09-11e5-888e-8af0e26b042f.png)

以及  `------` 为什么要充当 分隔符?

**Comment by xqin** [comment]
难道规则里的  `输入三个减号`  是写着玩的? @joyqi

**Comment by joyqi** [comment]
这应该是规则在撰写时的疏忽，没有交代清楚，我会马上修正

分隔符的处理没有问题，markdown的语法就是这么规定的。你可以试试github的处理
