### ISSUE TITLE
建议: 请问怎么在社区里删除自己账号及所有提出的问题和回答

### ISSUE THREAD

**Issue by xqin** [SegmentFault/report#204]
http://segmentfault.com/q/1010000003998328

如果没有官方的通道的话,那我就自己写脚本删除自己的问题和答案了.

对社区失望了, 社区对于那些刷分的人太容忍了,自己本身没有发现刷分的机制,而且对于举报一点反馈机制也没有,在QQ上给你们的人发消息,爱理不理的. 受够了, 请求删除本人在社区上的账号及所有相关的问题/回答.

**Comment by wtser** [comment]
相关的功能其实早就已经在开发中了，希望能给我们一点时间。

分析用户的行为日志，可以发现用户是否疑似刷分，这很简单(目前已经做到)，难的是对刷分的评判标准和处理的流程（目前正在抓紧实现）。

至于你提到的 qq 反馈问题没有及时给予回应，我想也许是你没找对合适的人，下次可以试着找我。

**Comment by xqin** [comment]
http://segmentfault.com/u/liangyi/rank
这个用户多次刷分, 上一次刷分是在 9月份, 在我举报之后,你们只是减一下积分.
然后前几天又举报了他一次(用小号给自己发的文章点赞)/收藏, 然后你们QQ上的那个人好像已经忘了这个账号之前因为严重刷分被处理过的事情.

然后这个账号  http://segmentfault.com/u/yawenina/rank  在QQ上给你们的相关人员发消息,让查一下是不是有刷分行为, 上午发一次消息没回我, 刚才又发一次没回我.


http://segmentfault.com/u/selfboot/rank 这个 初步怀疑也是在用小号刷分. 同一篇文章 在最近几天不停的被人点赞/收藏.


我已经受够了, 举报之后没有反馈, 以及对刷分者的容忍.  社区在处理刷分的账号之后,连个公告都不舍得发.

受够了!!!!!!!!!!!!!!!!!!

**Comment by xqin** [comment]
从我第一次举报有人严重刷分行为到现在已经过去2个月了.
我不知道你们还需要多长时间能想好应对措施.

**Comment by li2** [comment]
@xqin 担心你不上SF了，再把评论贴到这里：

过分刷声望的人，想必应该有非常强烈的炫分冲动，如果细加查看便可发现其中的猫腻，此时，炫的恐怕就是『腹内草莽』了。真币，假币，还不容易区分么。我为你点赞。

**Comment by xqin** [comment]
@li2  你好, 你的评论我已经收到了(sf有邮件通知), 不过我确实不再上sf这个社区了.
举报刷分我已经举报的累了, 社区没有合理的处罚机制, 已经没有待下去的意义了.
从我9月份举报第一个刷分者到现在, 他们都还没有想好对策,我不知道这样的社区待着还有什么意思.

让他们刷分玩去吧.

**Comment by li2** [comment]
@xqin 怎么说呢，成熟如StackOverflow也有人刷分，只是Stack设置的门槛较高，刷分不易而已，而且stack好像是没有文章的。。。也有人会钻法律的空子，既然是空子，就避免了被制裁。。。

我之前还发现过一个小团体，刷分程度恶劣到从网上搬来一模一样的问题和答案，互相问答。我之所以发现，是因为他们做的太恶劣了，没有采纳较早做出的优质答案，却采纳了另一个一句话答案。一下子就暴露了。简直污染了视线。

往差里说，有差劲的标题，没排版的代码，错别字，不通顺的句子，在答案里追加问题的描述。。。
往好里说，有认真的问题、讨论、答案，点赞感谢和声望，较好的问答内容呈现形式（相比传统的论坛跟帖）。
对我来说，在SF回答问题是有进步的，怎么讲呢，有些问题，我碰到过解决了，但你若让我立刻跟你描述这个过程，某些细节还是模糊，而当我回答这个问题，把它呈现在字面上，我就必须扣想一些细节，然后尝试用清晰的语言和逻辑描述它。

赚取声望的过程，也做了某些积累，而且私心里也是希望SF的声望对职业生涯有所帮助。所以也不希望它因为某些刷分行为而变得不被认可。

这大概就是一种『意义』吧。
如果认真答题的你留在这里，就往『好』里投了一个很大的分子。（好/(好+差)）
祝开心

**Comment by fenbox** [comment]
我们已经[完善了制裁机制并惩罚了](http://segmentfault.com/a/1190000004122125)相关人员，今后将进行更多改进，尽可能的减少此类行为

**Comment by xqin** [comment]
@fenbox  终于等到这一天了, 再过几天就2016年了.
@li2  我决定回社区了.

**Comment by xqin** [comment]
@fenbox  不是已经说有举报反馈机制了吗? 为什么我这几天举报的内容一点反馈都没有?

![image](https://cloud.githubusercontent.com/assets/1265888/12051850/ab232064-af43-11e5-98db-783bbd08b663.png)
