### ISSUE TITLE
忽略了个邀请，bug 一枚

### ISSUE THREAD

**Issue by XiaoLer** [SegmentFault/report#207]
![image](https://cloud.githubusercontent.com/assets/3905437/11395482/61a3e4ea-93a6-11e5-9b43-4779c06e2084.png)

**Comment by fenbox** [comment]
这个一个诡异的 bug，至今未找出原因 T___T

**Comment by XiaoLer** [comment]
现在这个 1 还显示着呢 这个应该不难查呀 计算的方法有问题嘛 😂

**Comment by lvye** [comment]
@XiaoLer 你好，“忽略全部未回答”可以重置计数。

![image](https://cloud.githubusercontent.com/assets/4340161/11652911/6aaa6f3a-9dd5-11e5-8ee5-2185e3917c3c.png)
