### ISSUE TITLE
头像剪切出现定位不准的问题

### ISSUE THREAD

**Issue by marsoln** [SegmentFault/report#208]
我上传一个宽高比大概2：1的图片 希望截取右下部分 然后定位总是偏左上了一些:dizzy_face:

环境如下

> Google Chrome   46.0.2490.86 (正式版本) m （32 位）
> 修订版本    e8926f681fbb840b4f389e7e692343d4505722ce-refs/branch-heads/2490@{#560}
> 操作系统    Windows 
> Blink   537.36 (@e8926f681fbb840b4f389e7e692343d4505722ce)
> JavaScript  V8 4.6.85.31
> Flash   19.0.0.245
> 用户代理    Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

PS：:smirk: 话说很巧的是 大概半个月前 知乎也出现了同样的问题，我也是跟他们提过了。
感觉。。。怪怪的:sweat:
是不是只有我传头像会裁剪呢 是不是太low了:cold_sweat:

**Comment by Integ** [comment]
谢谢反馈
正在处理中。

**Comment by marsoln** [comment]
不客气 我是粉丝 不知道贵司有没有文化衫之类的卖啊
