### ISSUE TITLE
piechart的小bug

### ISSUE THREAD

**Issue by marsoln** [SegmentFault/report#209]
呈现起来很简单 就是鼠标频繁的进入移出饼块,在mouseleave的动画没有完成,饼图的半径还没有恢复到原始值的时候再次触发mouseenter,就导致...

![image](https://cloud.githubusercontent.com/assets/7898688/11736006/5f52d96c-a003-11e5-9d91-602766764198.png)

:smile:

**Comment by wtser** [comment]
闲的蛋疼试了下，可以复现，就是有点无聊

**Comment by marsoln** [comment]
是有点小无聊，哈哈哈 :laughing:
