### ISSUE TITLE
建议：添加一个类似CSDN的结贴率的统计，添加对题主的采纳的顶踩。

### ISSUE THREAD

**Issue by marsoln** [SegmentFault/report#212]
不少用户问过问题之后，得到答案甚至不会给点个赞，更不要说标记已解决了。

我记得以前在CSDN上，每个问答帖都有个结贴率。

虽然答题都是自愿的，不只是为了赚积分。不过还是希望能有一种机制，促使提问的用户对这些愿意积极帮助他的同僚们给标记出予以采纳或者点个赞，不能说让每个题主抱着感激之情，但最起码不要让愿意付出时间作答的用户们感觉到自己用心的回答被白白地辜负掉。

另外，如果其他用户也可以对题主采纳的答案进行类似顶踩操作，这样一些没有含量的互刷互答的帖子，很快就会被其他用户踩出来，借助群众的力量维护了sf的社会治安。

以上

希望SF在未来越做越好

**Comment by lvye** [comment]
每次提问都会提示用户有未采纳的问题，自从加了这个提示之后，已经有大幅度的采纳率。但是我们不会强制用户去采纳，也不会让管理员去采纳答案。
一旦问题被发布出来，那么就属于公共内容，题主可以通过采纳，其它人可以通过赞和踩帮助后来看到的人进行快速地解决问题。
