### ISSUE TITLE
改进

### ISSUE THREAD

**Issue by dwqs** [SegmentFault/report#219]
![](http://i4.tietuku.com/958c56d464da914c.png)

1、会遮住最后一个标签的显示

![](http://i4.tietuku.com/20d3b95ea9949771.png)

2、鼠标放在 `撰写` 菜单  然后快速移动到 标签栏的 `...` 会出现图示的重叠

**Comment by wtser** [comment]
1. 这是设计对过多 tag 的处理
2. 这是一个设计问题，肯定存在谁挡住谁的问题
 @fenbox

**Comment by wtser** [comment]
新版设计已经上线，欢迎体验。
