### ISSUE TITLE
前端问题（SFv4）

### ISSUE THREAD

**Issue by anjianshi** [SegmentFault/report#220]
### 问题1
[feed 页面](http://segmentfault.com/timeline)一直显示一个旋转的箭头，不输出实际内容。

![2015-12-19_220550](https://cloud.githubusercontent.com/assets/5005012/11913381/1910345e-a69d-11e5-8b5e-1fd36c85fa10.png)

### 问题2
home 和 feed 页面都会在 console 里报两个错误。

![2015-12-19_220631](https://cloud.githubusercontent.com/assets/5005012/11913386/37dc4616-a69d-11e5-8d7e-155d03438f12.png)

### 测试环境
Chrome 47

**Comment by anjianshi** [comment]
P.S. 要怎么给 Issue 加 SFv4 的 label？普通人貌似没有这个权限

**Comment by joyqi** [comment]
我来帮你加

**Comment by wtser** [comment]
怎么 post 到 /api/log/frontend 都是404 啊，网络问题吗？

**Comment by anjianshi** [comment]
@wtser 
好像不是网络的问题。
以 GET method 访问 http://segmentfault.com/api/log/frontend 得到的是元首维护中的页面（HTTP Status 是 200）
以 POST method 访问得到的就是 404，内容是"杯具啊！可能这个页面已经飞走了"

下面是 request 详情
![req](https://cloud.githubusercontent.com/assets/5005012/11929645/fc98bf5e-a817-11e5-8b3f-158eb3765744.png)

**Comment by wtser** [comment]
sf 所有的请求如果没有带 token 就返回404，所以 timeline 报错也是因为接口返回404导致 js 报错。
但是为何请求会不带 token 就很让人费解。

**Comment by anjianshi** [comment]
上述问题已经不出现了，这次又变成对 http://segmentfault.com/api/user/notifications 的 AJAX 请求报 404 错误了，哈哈

**Comment by wtser** [comment]
已解决
