### ISSUE TITLE
全部标记为已读 没有效果

### ISSUE THREAD

**Issue by dwqs** [SegmentFault/report#222]
![image](https://cloud.githubusercontent.com/assets/7871813/11972045/7dee7ab6-a981-11e5-96e9-a3e1a2e190da.png)

点击 `全部标记为已读` 没有效果，未读消息的提示依然存在

mac 10.10.4  chrome 47.0.2526.106 (64-bit)

**Comment by wtser** [comment]
前端代码重新上线了，已解决，请再试试。
