### ISSUE TITLE
导航栏高亮问题

### ISSUE THREAD

**Issue by qq286735628** [SegmentFault/report#225]
![image](https://cloud.githubusercontent.com/assets/793007/11987887/185158bc-aa22-11e5-9a05-9d74d530357b.png)
![image](https://cloud.githubusercontent.com/assets/793007/11987888/1e0bc3aa-aa22-11e5-8f49-412a9d5e05f7.png)

产生过程: 点击导航上面的home或者feed
期望结果: 高亮当前导航
实际结果: 永远高亮的是feed
附件: 上图
环境: win10 x64, Chrome

**Comment by fenbox** [comment]
疑似你在后台同时启用了“动态首页”和“新版测试”功能，造成冲突。这是系统设置上的 bug，可暂时禁用“动态首页”功能解决

![image](https://cloud.githubusercontent.com/assets/360618/11999679/bebac116-aafe-11e5-8b9f-e19be5f877b4.png)
