### ISSUE TITLE
点标签进入标签页面时右侧排行榜头像问题

### ISSUE THREAD

**Issue by linxz** [SegmentFault/report#226]
http://segmentfault.com/t/html

头像上的圣诞帽跑了……

`img[class*=santa-hat-] {
    position: absolute;
    -moz-transform: rotate(45deg);
    -ms-transform: rotate(45deg);
    -webkit-transform: rotate(45deg);
    transform: rotate(45deg);
}`

缺少了具体的定位属性值。

`    top: -10px;
    left: 15px;`

* 操作系统： OS X 10.11.2
* 浏览器： Chrome Version 47.0.2526.106 (64-bit)

**Comment by fenbox** [comment]
感谢反馈，已修复 ^__^
