### ISSUE TITLE
滚动条自定义一下比较好

### ISSUE THREAD

**Issue by PuYart** [SegmentFault/report#228]
默认的滚动条太丑了。。。写个样式吧。

![](https://wt-prj.oss.aliyuncs.com/ccfa2bc367cc46fdb853a0aac6496f4d/7b872039-57e5-4c52-8320-dfe9b04ac05b.png?response-content-disposition=inline%3B%20filename%3Dsf-scrollbar.png&response-content-type=image%2Fpng&OSSAccessKeyId=fLlAbzSFOZAgHYIG&Expires=1450966993&Signature=5DWnXumq3CAINKb7ZAgPFIryA1Q%3D)

**Comment by wtser** [comment]
正在逐步替换中

**Comment by fenbox** [comment]
已替换

**Comment by PuYart** [comment]
恩恩，看到更新了 :)
