### ISSUE TITLE
使用体会：感觉新版的首页不实用

### ISSUE THREAD

**Issue by Junzki** [SegmentFault/report#231]
旧版的首页主要在于“问题”，新版的首页在于关注的人的动态。我觉得我关注的人的动态对于我来说并不是最想看到的，我最想在首页上看到的是与我喜欢的“话题”最相关的问题，不论是新问题还是热门问题。

**Comment by fenbox** [comment]
新版首页仍然是问题，可能你启用的仍然是旧版的测试版首页，而不是改进了导航栏的首页
