### ISSUE TITLE
XSS漏洞！

### ISSUE THREAD

**Issue by xiaohuilam** [SegmentFault/report#233]
![image](https://cloud.githubusercontent.com/assets/6964962/12001959/c4468626-ab2e-11e5-83b6-6b66c352b53f.png)

**Comment by xiaohuilam** [comment]
title中的<embed>和<object>未转义

**Comment by fenbox** [comment]
感谢反馈，这是开发人员改错了参数导致，目前已修复。
相关人员已经被开除。

**Comment by xiaohuilam** [comment]
擦。。。失误所致的话还是别开除吧。。。毕竟风险被控制住了
