### ISSUE TITLE
新版未翻墙google资源加载不了导致页面错乱

### ISSUE THREAD

**Issue by cocbin** [SegmentFault/report#234]
![image](https://cloud.githubusercontent.com/assets/11910291/12001993/73a6a416-ab2f-11e5-8e55-beb53b13dd81.png)
![image](https://cloud.githubusercontent.com/assets/11910291/12002005/9a5e8fa6-ab2f-11e5-9277-d7486d5bf8b2.png)

**Comment by fenbox** [comment]
感谢提交，已修复
