### ISSUE TITLE
一个非常非常严重的问题

### ISSUE THREAD

**Issue by yangbo5207** [SegmentFault/report#235]
markdown文章显示的布局，代码高亮依然很丑
能不能稍微花一点点时间把这个问题解决一下啊，如果实在忙不过来，我来帮你们写css样式都可以。丑得忍不了

写出来的文章展示效果好难看。

------

界面设计感觉一直是个非常大的问题，改版之后的界面也很丑 - -！

-----
代码块里面的字体能换一下吗，现在比较流行的"Fira Mono"， "Source Code Pro"都非常高大上，逼格爆满！

好吧，其他功能还是很满意，很棒！就是设计这一块，一点都不满意。感觉太掉档次了！！！

**Comment by yangbo5207** [comment]
今天突然发现字体变成Source Code Pro了，感动ing，希望高亮颜色能早点调整，期待ing

**Comment by lvye** [comment]
高亮是codemirror的，样式有很多，也算是众口难调，可能以后会在设置里加一个功能，可以选择高亮的样式。
