### ISSUE TITLE
未登陆状态下, 帖子的提问与回答区域, `更多` 是个摆设

### ISSUE THREAD

**Issue by xqin** [SegmentFault/report#238]
这个情况已于10天前, 向你们团队的某个人反馈过,现在还是未处理, 不知道结果是忽略这个问题了,还是没时间处理?

附当时的邮件截图:
![image](https://cloud.githubusercontent.com/assets/1265888/12005386/29ec77a2-abdd-11e5-9f29-d78ec97c2a59.png)

![image](https://cloud.githubusercontent.com/assets/1265888/12005390/56f79984-abdd-11e5-8dde-27b0f46ff2fc.png)

另外再顺便反馈一个小情况, 在用户登陆的情况下, 就不用再在页面中输出  `登陆` 时所用户的那个  模板了`loginModal`, 可以节省大约 4KB 的内容(对于不支持gzip的浏览器来说), 当浏览器支持gzip的时候,可以节省 1kb .
![image](https://cloud.githubusercontent.com/assets/1265888/12005402/1ce24874-abde-11e5-8ce1-9cbab679d810.png)

再另外对于这种 模板类的东东, 当内容比较多的时候不建议放在页面里, 可以考虑做为资源单独保存为单个文件, 这样除第一次使用时会加载一次, 其他时间可以读浏览器缓存/CDN等, 这样服务器不用每次都在页面上输出, 对用户以及服务器都有好处.

**Comment by kumfo** [comment]
我靠，竟然是我给的回答？我申请的内测好像都还没通过呢。唉

**Comment by wtser** [comment]
已做调整

**Comment by xqin** [comment]
@wtser  已做调整是指已经改好了, 我们可以看到效果的意思吗? 还是说只是你本地已经改了,但还没发布到线上?

我目前在 sf.gg 上看到在未登陆情况下 点开   `更多` 还是空白.
![image](https://cloud.githubusercontent.com/assets/1265888/12110995/d586550a-b3cc-11e5-8df8-67b00ca82c52.png)

**Comment by wtser** [comment]
只上了新版，旧版暂不做维护
