### ISSUE TITLE
内测反馈

### ISSUE THREAD

**Issue by kumfo** [SegmentFault/report#239]
我已经申请内测了，虽然我才三百多分，这个分数是因为我刚玩segmentfault不久，不过希望能给我通过，这种程序员交流论坛我还是比较感兴趣的；虽然我赶不上许多大牛。

**Comment by fenbox** [comment]
你可以提交到 http://t.cn/R4A2mNY 来，我们会依次开通。
github 这里只是处理使用，相关人员可能看不到。
