### ISSUE TITLE
请问 markdown 编辑器里键盘上的  `pageup/pagedown` 键 在编辑器里起什么作用?

### ISSUE THREAD

**Issue by xqin** [SegmentFault/report#240]
编辑器说明及测试页面:

http://segmentfault.com/markdown

在最后面的编辑器里按 `pagedown`->`pageup`->`pagedown` 就能看到如下效果了
![image](https://cloud.githubusercontent.com/assets/1265888/12007141/1c7c394a-ac32-11e5-9df7-a32b09249451.png)

然后页面滚动条往上移动后的界面如下:
![image](https://cloud.githubusercontent.com/assets/1265888/12007146/31ec51f2-ac32-11e5-9b1d-c32bbc067982.png)

请确认一下,这个特殊功能,还是bug?

**Comment by fenbox** [comment]
这是一个 bug

**Comment by Integ** [comment]
在编辑器中 PageDown/PageUP 可以优先对编辑器上下翻页
chrome
再次测试，没有发现问题

**Comment by xqin** [comment]
Windows 7 x64 平台下, chrome 44/47 隐私模式下(未加载任何插件), 仍然可以重现该问题.

**Comment by xqin** [comment]
然后我将markdown的连接发给QQ群里的其他朋友, 也有人反馈有重现的.
![image](https://cloud.githubusercontent.com/assets/1265888/12107084/08c9b1b8-b3a1-11e5-9772-ecd5a081011c.png)

所以这个问题肯定是存在的.
在编辑区域 获得焦点的情况下, 按以下顺序按键.
`pagedown->pageup->pagedown->pageup->pagedown`
可能MAC下不能重现, 但windows下, 我已经在好几台机器上重现了.

浏览器是chrome

**Comment by Integ** [comment]
谢谢反馈，今天再研究下

**Comment by fenbox** [comment]
fixed

**Comment by xqin** [comment]
经确认该问题并没有修复.
![sf](https://cloud.githubusercontent.com/assets/1265888/12409227/0bfe7e1a-bea3-11e5-9ded-4da2d07fb15d.gif)
