### ISSUE TITLE
新版体验

### ISSUE THREAD

**Issue by xwartz** [SegmentFault/report#241]
系统： Mac
浏览器： Chrome

1. 帖子点开之后，标题不能复制

2. 导航条， home，feed 两个地方 hover 效果是加下划线，其他都不是，感觉有点怪哦。。

**Comment by fenbox** [comment]
1. 标题为什么不能复制呢？
2. home, feed 和后面的 tag 有不同的意义，所以进行了区分

**Comment by xwartz** [comment]
标题的 a 标签 `display: block` 之后，宽度变成整条了，从后往前就很难复制了。。
