### ISSUE TITLE
在开启新版之后, 关闭浏览器, 然后从其他位置点连接, 打开 sf 上面的帖子, 会跳到首页, 但旧版不会

### ISSUE THREAD

**Issue by xqin** [SegmentFault/report#242]
1. 登陆的时候选择 `记住登录状态`, 然后完成登陆.
2. 在 `实验功能` 中 `启用`  `新版测试`,  提交设置后, 关闭浏览器.
3. 随便从其他地方 (比如这里: http://segmentfault.com/q/1010000004207721) 点开 sf 上的帖子连接.

在 sf 跳转之后, 跳的是首页,而不是你点开的这个连接.

下图为HTTP请求/响应的内容:
在启用新版之后, 关闭浏览器, 然后直接打开 某个帖子的时候 的结果

![image](https://cloud.githubusercontent.com/assets/1265888/12009808/d8609ce6-acc3-11e5-85e5-18f3af7dd8dc.png)

在设置为不启用之后(旧版), 关闭浏览器, 然后再打开浏览器, 直接打开某个帖子地址时的结果:
![old](https://cloud.githubusercontent.com/assets/1265888/12009818/6352a092-acc4-11e5-8ec1-fc3dbc00cec8.png)

期望的结果为:  在新版中 由 `sf_remember` 完成快速登陆之后, 直接显示帖子的内容, 而不是再跳回首页(即与旧版保持一致).

**Comment by xqin** [comment]
因为在提 issue 的时候, 没找到怎么添加  `label` 的方法, 所以  `SFv4` 的标签, 我添加不了, 麻烦你们的工作人员, 加一下, 谢谢.

**Comment by lvye** [comment]
已经修复。

**Comment by xqin** [comment]
经测试已确认修复, 可以 close 啦 :)
