### ISSUE TITLE
SFv4 版本在展示回复时的效果时, 不如旧版好处, 且在相同宽度下头像和昵称都换行了

### ISSUE THREAD

**Issue by xqin** [SegmentFault/report#243]
开启两个窗口, 相同宽度, 新旧版本的展示效果:

![image](https://cloud.githubusercontent.com/assets/1265888/12012988/54e0867c-ad47-11e5-9bcb-d1cc60ae0b80.png)

下图为新版正确情况下的效果, 但我个人更喜欢旧版的这种排版风格(回复者的信息在帖子的固定位置展示, 而在新版中, 这些信息在回复的内容后面, 会跟着回复内容的多少, 而在不同的位置, 且把 昵称和声望放在右下角, 是想让提问者先看内容, 再看是谁回复的? 以降低提问者因声望值, 而对回复者采纳时的影响?)
![image](https://cloud.githubusercontent.com/assets/1265888/12013017/bd5362d8-ad47-11e5-8f77-3b896ba8032a.png)

另新版中, 使用了大头像 和两行的高度来展示 昵称和声望,  会让左边的操作区域凭空多出来一片空白区域.

所以我所期望的效果是: 此处的改动还保持原样.

**Comment by kumfo** [comment]
乱版了

**Comment by wtser** [comment]
已做调整
