### ISSUE TITLE
提问页面出现一些闪动

### ISSUE THREAD

**Issue by aisuhua** [SegmentFault/report#245]
不多说，上图

![提问页面出现一些闪动](http://7xj8ix.com1.z0.glb.clouddn.com/sf_01.gif)

看不到图的话，看这里吧 http://7xj8ix.com1.z0.glb.clouddn.com/sf_01.gif

闪动过后，大概1分钟后，页面会出现刚刚闪动的导航条。

**Comment by aisuhua** [comment]
浏览器：Google Chrome 
版本： 46.0.2490.71

**Comment by fenbox** [comment]
这确实是个 bug，我们将尽快对标签输入这块的交互方式进行一次改进

**Comment by kumfo** [comment]
其实发布文章也存在这个问题的，应该是发布地方都调用这个js的问题
