### ISSUE TITLE
新版内测想法

### ISSUE THREAD

**Issue by kumfo** [SegmentFault/report#246]
申请的内测权限终于通过了；
1.首先，接触segmentfault是在一年前，不过那时候没有关注，大概在两个月前，去梦想小镇玩，又看到了这个熟悉的segmentfault，于是我决定注册一个账号；虽然我的问题比较少，但是给别人提供 建议和想法的感觉还是非常好的，也比较喜欢segmentfault这种氛围，大家一起交流和学习，也可以装装逼。这里跑题了。
2.好了，说说用上新版的感觉吧，首先，新版的首页感觉还是比较惊喜的，旧版的首页和布局感觉很厚重，或者是是有一种沉闷感，但是新版就感觉很轻快活泼了。而且展现的都是想关注的内容，这种感觉比较好，可以很快看到自己想解答的问题。
3.Bug测试，后续更新会贴上来。

**Comment by kumfo** [comment]
对于这个热门的排序问题，我每次看热门的都是那些东西，我已经不想看了，特别是已关闭的问题，展示在热门我觉得更没啥必要了。我想展示热门问题的初衷应该是想让这个热门的东西对大家有帮助对吧？如果展示没用了的问题再热门，我觉得会误导，像这种争议的问题，已经关闭了，如果去浏览，想交流嘛，没法交流，不交流嘛，又揪心。

**Comment by kumfo** [comment]
回答问题的时候，这个人布局放在下面，我开始想 看是谁回答的都没法看，而且我想要吐槽的是，竟然没有发私信的功能，有时候想单独两个人交流一下都没法实现，不知道是不是我没习惯的原因，如果需要单独交流难道我还要发个问题啊，但是与编程无关的不可以发。

**Comment by kumfo** [comment]
回答问题的时候，这个人布局放在下面，我开始想 看是谁回答的都没法看，而且我想要吐槽的是，竟然没有发私信的功能，有时候想单独两个人交流一下都没法实现，不知道是不是我没习惯的原因，如果需要单独交流难道我还要发个问题啊，但是与编程无关的不可以发。

**Comment by vickyqi** [comment]
消息里面没法区分已读还是未读，我是强迫症，有一次出了BUG，点了“全部标记为已读”按钮，但是还有显示有一个未读消息，而且那个“全部标记为已读”按钮也不见了，刷新也没用，害得我一个一个消息点了一遍，哭死

**Comment by kumfo** [comment]
@vickyqi 同感

**Comment by fenbox** [comment]
"已关闭问题"在热门问题中的权重已降低
