### ISSUE TITLE
是我无聊, 关于sf的页面中引入的 debug.js 的一些建议

### ISSUE THREAD

**Issue by xqin** [SegmentFault/report#247]
该文件的URL地址为.: http://static.segmentfault.com/v-567d12e1/global/js/debug.js

代码如下:
```

/*
    监控js错误并上报
    wtser@sf.gg
 */
window.onerror = function(msg, url, line, col, error) {
  if (msg !== "Script error." && !url) {
    return true;
  }

  /*
      采用异步的方式
      我遇到过在window.onunload进行ajax的堵塞上报
      由于客户端强制关闭webview导致这次堵塞上报有Network Error
      我猜测这里window.onerror的执行流在关闭前是必然执行的
      而离开文章之后的上报对于业务来说是可丢失的
      所以我把这里的执行流放到异步事件去执行
      脚本的异常数降低了10倍
   */
  setTimeout(function() {
    var c, data, ext, f, match;
    data = {};
    col = col || (window.event && window.event.errorCharacter) || 0;
    data.userId = document.querySelector("#SFUserId").getAttribute('value');
    data.url = url;
    data.line = line;
    data.col = col;
    data.msg = msg;
    data.targetUrl = location.href;
    if (!!error && !!error.stack) {
      data.msg = error.stack.toString();
    } else if (!!arguments.callee) {
      ext = [];
      f = arguments.callee.caller;
      c = 3;
      while (f && c > 0) {
        c = c - 1;
        ext.push(f.toString());
        if (f === f.caller) {
          break;
        }
        f = f.caller;
      }
      ext = ext.join(",");
      data.msg = ext || msg;
    }
    if (data.userId) {
      match = data.targetUrl.match(/\/\/[\s\S]*\//);
      if (!match) {
        return false;
      }
      if (match[0].search('segmentfault') !== -1) {
        console.warn(data);
        return $.post('/api/log/frontend', data);
      }
    }
  }, 0);
  return false;
};
```

第1个问题:  `document.querySelector` 这个API, IE8 以前的浏览器是不支持的.

第2个问题:  经确认 `#SFUserId` 这个节点是一个隐藏的 `input`, 取值的话, 可以直接 `.value`,
又因为是使用ID命中的, 所以推荐直接使用 `document.getElementById('SFUserId').value` 来取值.

第3个问题: 纵观整个代码, 最后数据上报与否, 与是否有 `userId` 有关, 所以该条件检测, 是否可以放在最上面. 或者更直接一点, 未登陆用户, 不输出这个`script`标签? 再或者 先检测有没有 `userId` 再去绑定事件, 这样可以不用在 `error` 触发的时候, 每次都去读这个值(因为这个值, 在页面加载之后又不会变).

第4个问题: 在有 `userId` 的情况下, 有一个 `match` 和 `search` 的动作, 在这两个条件都成立的时候, 才会上报, 是否可以直接用一个 正则表达式来完成该项检测?

第5个问题: 在 `$.post` 之前有一个 `console.warn` 的动作, 在不支持 `console` 这个对象的浏览器下, 当触发 `window.error` 的时候, 会继续 `error`.

第6个问题: 在上报的时候使用的是 `$.post`, 依赖于 `jQuery`, 可 `jQuery` 是在后面加载的, 故在 `jQuery` 未完成加载之前, 有其他的脚本发生错误, 触发 `window.onerror` 之后, 因为没有 `$` 对象, 这里会继续出错.

第7个问题:  如果有后续的其他脚本使用`window.onerror`对它进行覆盖,将会导致`debug.js`中的代码失效.

以上均为个人观点, 可选择性忽视上面提出的问题, 也有可能是我分析的不对.
比如,你们可能对JS代码的兼容性要求, 不考虑小于IE8以前的浏览器等.

**Comment by kumfo** [comment]
感觉这个分析得很详细。

**Comment by wtser** [comment]
Hi @xqin 

问题5：如果错误发生时，jquery 都还未载入，那么此类的问题应该当即就发现了，而不是通过上报来发现。

问题3 ：之前没有做这层判断，导致有大量的误报，为了方便定位解决用户的问题，临时加了登录用户判断。

问题4：主要是考虑到 排除部分浏览器插件引起的 bug。正则我不精通啊。

问题7 ：伪命题
问题1 ： 暂不考虑低端浏览器
问题2 ：你确定你这样的写法正确吗？

**Comment by xqin** [comment]
问题2, 我刚去认真查看了一下, 居然是 `meta` 标签  =,=
```
<meta name="userId" value="1030000000334890" id="SFUserId"/>
```

**Comment by wtser** [comment]
问题3 ： 最后数据上报与否 取决于有没有错误发生，否则是不会执行这里的代码的

**Comment by xqin** [comment]
问题3: 最后的 `$.post` 是否执行与 当前页面是否有 `if(data.userId)` 来决定的.

所以如果用户进入当前页面的时候,是未登陆的(即没有userid的), 则完全不用引入 `debug.js` 这个文件.
因为即便最终产生错误, 但因为没有 userid, 所以不会上报.

另外,如果你能预测到你的代码出错误,那么你就不需要用 `window.onerror` 来检测js错误了,直接修复错误代码就可以了, 所以这里提出的问题就是建立在 页面中其他地方的js产生了错误, 进到了你的 `onerror` 里 的这个前提条件下的.(这个是回复你 `最后数据上报与否 取决于有没有错误发生` 这句的)

如果你还看不明白, 那我就不知道要跟你说什么了.

```javascript
    if (data.userId) {//注意看这句, 以及这个值是怎么来的
      match = data.targetUrl.match(/\/\/[\s\S]*\//);
      if (!match) {
        return false;
      }
      if (match[0].search('segmentfault') !== -1) {
        console.warn(data);
        return $.post('/api/log/frontend', data);
      }
    }
```

**Comment by xqin** [comment]
`脚本的异常数降低了10倍` 
`问题3 ：之前没有做这层判断，导致有大量的误报，为了方便定位解决用户的问题，临时加了登录用户判断。`

在你加了 `data.userId` 之后, 你只上报了 登陆后的用户, 在页面中产生的错误, 而忽略了,没有登陆的用户,在使用的过程中产生的错误, 所以你的错误数 下降了.

这个下降并不是因为你用了 `setTimeout` 而产生的效果, 而是因为你过滤了, 未登陆用户所产生的js错误.

@fenbox  @joyqi  @Integ   不知道你们最初的需求就是 只监测, 登陆用户在使用过程中的js错误, 而不管未登陆用户的?

**Comment by wtser** [comment]
@xqin setTimeout 是针对使用手机浏览器或者微信访问sf站点做的，请你不要断章取义。
