### ISSUE TITLE
个人主页中 `擅长标签` 这个区域 有个横向滚动条, 不知道能不能处理一下

### ISSUE THREAD

**Issue by xqin** [SegmentFault/report#249]
![image](https://cloud.githubusercontent.com/assets/1265888/12017423/3798a910-ad91-11e5-9b32-189a5e5c2783.png)

windows 平台下 的 chrome/firefox 都是这种结果.

目前的宽度是可以显示整个内容的, 但还是有滚动条, 是否可以处理一下?

这个问题不分新旧版, 都存在.
且这个问题我之前和 姜上 说过, 但可能QQ上说效果不好, 所以还是提个 issue 吧.

**Comment by fenbox** [comment]
我们马上会上新版的个人 profile，将使用其他方式代替饼图
