### ISSUE TITLE
关于通知提示的问题

### ISSUE THREAD

**Issue by kumfo** [SegmentFault/report#251]
这个图片好像没法上传，不知道为什么，我看到有消息通知，点进去看是有好友加我，然后我点哪个好友的进到了好友的空间，但是没法消除这个通知，我点了所有通知设为已读也不行。
然后我点击查看所有，发现有新的好友关注，但是显示是我之前的好友那一列，没列出新的好友，进去之后发现新好友和旧的好友列在以前，点一下新的那个好友就可以了。不方便啊！

**Comment by kumfo** [comment]
还是不行。。。

**Comment by wtser** [comment]
已做了改进
