### ISSUE TITLE
我的回答被恶意踩

### ISSUE THREAD

**Issue by kumfo** [SegmentFault/report#252]
我挺不爽的，我回答得非常详细，而且非常完善， 竟然被踩了，我是不是很悲催？
啊啊啊啊啊 ！！！！！
要是知道谁恶意踩的，可以举报就好了。唉
附上链接：
http://segmentfault.com/q/1010000004225321?_ea=535292

**Comment by fenbox** [comment]
对于恶意踩的行为，我们将从严惩罚。
你可以提交申诉管理员将进行核查（目前功能入口还不明显）
![image](https://cloud.githubusercontent.com/assets/360618/12061583/2cd11d6a-afc5-11e5-926c-37af16ccf185.png)
