### ISSUE TITLE
希望能够加入“关闭问题”这个功能！

### ISSUE THREAD

**Issue by KyleTung** [SegmentFault/report#254]
产生过程: 一开始有问题了上 SegmentFault 提问，但是没有人回答出正确问题，最后自己又解决了，所以此时希望关闭这个问题，防止误导别人。

期望结果: 添加“关闭问题”功能

环境: Windows10，Chrome

**Comment by fenbox** [comment]
这种情况建议自己回答并采纳自己的答案作为问题的完结。
只有讨论形等宽泛且无法获得确切结果的问题才能关闭
