### ISSUE TITLE
无法开通专栏问题

### ISSUE THREAD

**Issue by liutxer** [SegmentFault/report#255]
新人希望开通专栏,写写文章,但是进入专栏显示如下图.

![2016-01-03 11 45 01](https://cloud.githubusercontent.com/assets/16056571/12077198/42f6a5a2-b212-11e5-9589-bde3a96be8ee.png)

上面提示说我没有开通专栏,但是下面又说我已经开通了专栏.

结果无法开通专栏.

**Comment by wtser** [comment]
ok，提供下您的用户名，我们来查查

**Comment by liutxer** [comment]
用户名: liutxer

**Comment by wtser** [comment]
已在后台帮你手动开通，请再试试

**Comment by liutxer** [comment]
我发现在我的档案中填写了个人简介,但是在我的主页里没有显示.
![2016-01-05 12 31 23](https://cloud.githubusercontent.com/assets/16056571/12109320/bf1f974c-b3bb-11e5-9dc2-b0b1d5cc0bc4.png)
用户名: liutxer

**Comment by wtser** [comment]
我的档案是投递简历时候用的，你说的这个简介是在账号设置里设置

**Comment by welkin-qing** [comment]
怎么开通专栏?
