### ISSUE TITLE
v4新建笔记总是保存两份？

### ISSUE THREAD

**Issue by savokiss** [SegmentFault/report#257]
产生过程: 新建笔记
期望结果: 正常保存一份
实际结果: 保存两份

环境: win7, firefox43.0.3

我以为是我手抖，然后删了一个，第二个笔记还是保存两份，两份的内容和时间都完全一样
好吧chrome好像没这个问题
我的firefox貌似发了两个网络请求o(╯□╰)o...

**Comment by wtser** [comment]
发现 @geminiwen  and @Integ  头像很接近
