### ISSUE TITLE
评论时写错字了、有新的资料需要添加，然而却不被允许

### ISSUE THREAD

**Issue by lilydjwg** [SegmentFault/report#261]
直到经过一定的时间，当我已经忘记接下来要做什么修正和优化的时候。

**Comment by wtser** [comment]
https://github.com/SegmentFault/report/issues/262

**Comment by lilydjwg** [comment]
这不是同一个问题。 #262 是关于编辑次数的，而本 issue 是关于编辑频率的。

我希望做出几次连续的修正和补充，却被频次限制拦了下来。我觉得如果你们真要限制频次的话，可以允许一个短时间内的 burst。这样用户连续回复多人，或者连续修正评论时就不会遇到问题了。

**Comment by lilydjwg** [comment]
Closing because its function has been moved to https://board.segmentfault.com/.
