### ISSUE TITLE
还是建议sf在个人的声望列表中增加展示产生该条记录的用户

### ISSUE THREAD

**Issue by xqin** [SegmentFault/report#264]
问题连接:  http://segmentfault.com/q/1010000004279120
目前该问题已经被删除, 我想请管理员帮我查一下,这一系列操作是由这个帖子的发起人操作的,
还是内部人员或者社区里的某个用户操作的.

![image](https://cloud.githubusercontent.com/assets/1265888/12219794/95a45414-b78c-11e5-8382-875773eb569e.png)

![image](https://cloud.githubusercontent.com/assets/1265888/12219799/d2cc2b1e-b78c-11e5-8603-3451bbd39c7e.png)

大半夜的回答了他的问题(解决了他的问题), 没过几分钟, 就受到了, 取消赞, 取消采纳, 答案被忽略 的这种待遇. 谁能告诉我这是谁干的.

**Comment by lvye** [comment]
是题主自己弄的，然后他最后把问题和内容改成了“已解决”，有人举报，我们进行了处理并警告。

**Comment by xqin** [comment]
好吧.

刚刚还赞我的答案并采纳呢, 问题解决后, 就立马就取消/忽略我的回答.
借用星爷的一句话 `这大起大落太快,真是太刺激了.`    :P

**Comment by lvye** [comment]
还是会有一些人当做论坛来使用，不过的确需要更详细的日志来告诉用户发生了什么。
