### ISSUE TITLE
网站使用的字体

### ISSUE THREAD

**Issue by sandmanman** [SegmentFault/report#266]
我是来吐槽的，WIN下页面字体真的是又粗又模糊，大段的内容看着真的有些累的。
font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,STHeiti,"Microsoft Yahei",SimSun,sans-serif;

还是说这是为了区别特色。

**Comment by fenbox** [comment]
新版网站字体已做了修改，你可以尝试在【账号设置】的【实验室】种开启
