### ISSUE TITLE
列表大于10时，markdown 解析错误

### ISSUE THREAD

**Issue by aisuhua** [SegmentFault/report#269]
如下图：
![](http://7xj8ix.com1.z0.glb.clouddn.com/sf-issue-02.png)

当列表大于10时，11以后的就会新换一行。
期望结果：不要换行。

**Comment by wtser** [comment]
似乎无法复现
![image](https://cloud.githubusercontent.com/assets/2093743/12528052/f59ae836-c1c5-11e5-82bf-336b1fe02c76.png)

**Comment by aisuhua** [comment]
我刚刚又试了一下，问题还是存在，在 [撰写文章页面](http://segmentfault.com/write)。截了一个动态图  3M ，可能要等一会，你看看

![](http://7xj8ix.com1.z0.glb.clouddn.com/sf-issue-02.gif)

**Comment by aisuhua** [comment]
点开看快一些，http://7xj8ix.com1.z0.glb.clouddn.com/sf-issue-02.gif

**Comment by wtser** [comment]
列表最前面似乎有空格？

**Comment by aisuhua** [comment]
应该与空格没有关系。我试过，是这样的，就是当“列表项目”的下标到了双位数（比如：10、11....），当第一次出现两个双位数时，比如：1...9、10、11、12 ... 此时 10 - 11 之间会出现断层。

第二种情况是：如果“列表项目” 的下标到了 11，然后它后面的下标如果是小于双位数，比如：1....9、10、11、5 ...。此时的 10 - 11 之间出现断层，而且 11 - 5 之间同样解析不对，5 被解析成了 1.

github 不方便上传图片，所以我在 SF 开贴了，可以看看这里：http://segmentfault.com/q/1010000004357298

还有一点，不知道 SF 官网开通的“建议反馈 http://board.segmentfault.com/ ” 栏目不能上传图片，这样子对于反馈 bug 和问题不太方便，希望官网重视一下。

**Comment by wtser** [comment]
麻烦提供下原始数据

**Comment by wtser** [comment]
![image](https://cloud.githubusercontent.com/assets/2093743/12541419/d7e9e304-c351-11e5-9e95-dddb19ddb027.png)

**Comment by aisuhua** [comment]
谢谢！
