### ISSUE TITLE
撰写答案无法显示提交按钮。

### ISSUE THREAD

**Issue by maxtrunk** [SegmentFault/report#271]
网站出错了。撰写答案无法显示提交按钮跟JS错误。
![screen shot 2016-02-16 at 10 16 01 pm](https://cloud.githubusercontent.com/assets/3771896/13098892/eae4fbbe-d4fa-11e5-848c-e3b688a5f9b5.png)
![screen shot 2016-02-16 at 10 15 43 pm](https://cloud.githubusercontent.com/assets/3771896/13098894/ede8bde6-d4fa-11e5-9405-61e9f58affe4.png)

**Comment by wtser** [comment]
你好，我测试了一下，没有发现问题，请问你的网络运营商是哪家？提供一下出问题的页面 url ，谢谢

**Comment by maxtrunk** [comment]
几乎是任何连接都有这个问题呢。前几天没事儿。火狐，谷歌，360都有这个问题。跟营运商有啥关系，dns重新定向了？
https://segmentfault.com/q/1010000004445379

![screen shot 2016-02-16 at 10 45 16 pm](https://cloud.githubusercontent.com/assets/3771896/13099313/00fbb89e-d4ff-11e5-938e-1a4b8a4b9ab8.png)

**Comment by wtser** [comment]
静态资源都是放在 upyun 上的 ，sf-static.b0.upaiyun.com/v-56b1c937/
奇怪的指向

是不是所有的 js 操作都跪了

**Comment by wtser** [comment]
确定没有翻墙吗

**Comment by maxtrunk** [comment]
哦 原来如此，有翻，不过前几天还好。那我明白了，谢谢啊
