### ISSUE TITLE
找不到回答问题的提交按钮

### ISSUE THREAD

**Issue by kimljj** [SegmentFault/report#276]
您好，在Android上一切正常，但在桌面版火狐（Version 46）和 Chrome (Version 50)上找不到提交按钮。IE 11 正常。

Console 看到下面的报错
Script from origin 'https://dfnjy7g2qaazm.cloudfront.net' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://segmentfault.com' is therefore not allowed access.
template.js:10

Uncaught ReferenceError: define is not defined

**Comment by wtser** [comment]
关掉你的全局翻墙
