### ISSUE TITLE
思否网站加载时间非常久，并且加载不出来静态资源

### ISSUE THREAD

**Issue by wangxiaocuo** [SegmentFault/report#286]
虽然这里不再处理issue，让去网站，但是我网站打不开啊。死循环。

如图，所有 CSS 文件加载失败，`umi.js` 加载失败，所有图片资源 403。

人在苏州，切换了各种网络和关闭所有 VPN 尝试了，全都不行。

是地区 cdn 未分发吗？希望官方能看到我的 issue，尽快解决。

![image](https://user-images.githubusercontent.com/16472134/145918516-27fcda7c-a063-44a0-9604-16f3be9e6609.png)
![image](https://user-images.githubusercontent.com/16472134/145918558-7a093267-119f-4a43-b198-c4166222c7bc.png)

---

经过尝试，手机4g打开可以，电脑连4g不能打开......

**Comment by joyqi** [comment]
请在不能访问的终端ping一下cdn.segmemtfault.com，把结果贴上来

**Comment by wangxiaocuo** [comment]
> 请在不能访问的终端ping一下cdn.segmemtfault.com，把结果贴上来

我又研究了下，应该是公司网络的问题，同事电脑也不能打开......电脑连4g不能打开的问题是因为DNS，改了个DNS就好了。

**Comment by joyqi** [comment]
你用原来的dns也ping一下，看看指向哪里了

**Comment by wangxiaocuo** [comment]
> 你用原来的dns也ping一下，看看指向哪里了

![image](https://user-images.githubusercontent.com/16472134/145925644-736dbbcb-8ec3-44be-aae8-1cc9d20ca432.png)

**Comment by joyqi** [comment]
域名写错了 `cdn.segmentfault.com`

**Comment by wangxiaocuo** [comment]
> cdn.segmentfault.com

![image](https://user-images.githubusercontent.com/16472134/145926162-abf037ce-0e1c-48c1-be4b-227cc539c316.png)

**Comment by joyqi** [comment]
解析应该没问题啊，看来是这个节点出问题了，你们是哪个地方什么运营商的网络

**Comment by wangxiaocuo** [comment]
> 解析应该没问题啊，看来是这个节点出问题了，你们是哪个地方什么运营商的网络

应该是公司运维禁了网段，没事啦
